IF
  GlobalTimerExpired("HordeTimer","AR3025")
  Global("SpawnSpirit","AR3025",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnSpirit","AR3025",1)
    TriggerActivation("Tran3019",TRUE)
    CreateCreatureObjectEffect("FSSPIRA","SPFLESHS",Player1)
    ActionOverride("FSSPIRA",StartDialogNoSet(Player1))
END

IF
  Global("Iasibelasks","AR3025",0)
THEN
  RESPONSE #100
    SetGlobal("Iasibelasks","AR3025",1)
    ActionOverride("Pool 1",CreateItem("MISC07",90000,0,0))
END