IF
  See(NearestEnemyOf(Myself))
  XPLT(Player1,3400000)
  Global("Iaprep","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaprep","LOCALS",1)
    SetGlobal("Iaprotect","LOCALS",2)
    SetGlobal("Iaskins","LOCALS",3)
    SetGlobal("Ialowerfire","LOCALS",3)
    SetGlobalTimer("pfmw","LOCALS",24)
    ReallyForceSpell(Myself,DRAGON_STONE_SKIN)
    ReallyForceSpell(Myself,PROTECTION_MAGIC_WEAPON_NOEFF)
END